language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

script:
  # Validate composer.json file.
  - composer validate
  # Try to install all requirements.
  - composer install

notifications:
  email:
    - albertogviana@gmail.com